// Generated by tools/reference/generate_osce_specs.py from the pinned Opus model exports.
#![allow(dead_code, unused_parens, clippy::excessive_precision)]
use super::{LayerSpec, OwnedLayer};
use crate::dnn_weights::{WeightBlob, WeightError};
pub(crate) const LACE_PREEMPH: f32 = 0.85;
pub(crate) const LACE_FRAME_SIZE: usize = 80;
pub(crate) const LACE_OVERLAP_SIZE: usize = 40;
pub(crate) const LACE_NUM_FEATURES: usize = 93;
pub(crate) const LACE_PITCH_MAX: usize = 300;
pub(crate) const LACE_PITCH_EMBEDDING_DIM: usize = 64;
pub(crate) const LACE_NUMBITS_RANGE_LOW: usize = 50;
pub(crate) const LACE_NUMBITS_RANGE_HIGH: usize = 650;
pub(crate) const LACE_NUMBITS_EMBEDDING_DIM: usize = 8;
pub(crate) const LACE_COND_DIM: usize = 128;
pub(crate) const LACE_HIDDEN_FEATURE_DIM: usize = 96;
pub(crate) const LACE_NUMBITS_SCALE_0: f32 = 1.0983514785766602;
pub(crate) const LACE_NUMBITS_SCALE_1: f32 = 2.0509142875671387;
pub(crate) const LACE_NUMBITS_SCALE_2: f32 = 3.5729939937591553;
pub(crate) const LACE_NUMBITS_SCALE_3: f32 = 4.478035926818848;
pub(crate) const LACE_NUMBITS_SCALE_4: f32 = 5.926519393920898;
pub(crate) const LACE_NUMBITS_SCALE_5: f32 = 7.152282238006592;
pub(crate) const LACE_NUMBITS_SCALE_6: f32 = 8.277412414550781;
pub(crate) const LACE_NUMBITS_SCALE_7: f32 = 8.926830291748047;
pub(crate) const LACE_PITCH_EMBEDDING_OUT_SIZE: usize = 64;
pub(crate) const LACE_FNET_CONV1_OUT_SIZE: usize = 96;
pub(crate) const LACE_FNET_CONV1_IN_SIZE: usize = 173;
pub(crate) const LACE_FNET_CONV1_STATE_SIZE: usize = (173 * (0));
pub(crate) const LACE_FNET_CONV1_DELAY: usize = 0;
pub(crate) const LACE_FNET_CONV2_OUT_SIZE: usize = 128;
pub(crate) const LACE_FNET_CONV2_IN_SIZE: usize = 384;
pub(crate) const LACE_FNET_CONV2_STATE_SIZE: usize = (384 * (1));
pub(crate) const LACE_FNET_CONV2_DELAY: usize = 0;
pub(crate) const LACE_FNET_TCONV_KERNEL_SIZE: usize = 4;
pub(crate) const LACE_FNET_TCONV_STRIDE: usize = 4;
pub(crate) const LACE_FNET_TCONV_IN_CHANNELS: usize = 128;
pub(crate) const LACE_FNET_TCONV_OUT_CHANNELS: usize = 128;
pub(crate) const LACE_FNET_GRU_OUT_SIZE: usize = 128;
pub(crate) const LACE_FNET_GRU_STATE_SIZE: usize = 128;
pub(crate) const LACE_CF1_FILTER_GAIN_A: f32 = 0.690776;
pub(crate) const LACE_CF1_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const LACE_CF1_LOG_GAIN_LIMIT: f32 = 1.151293;
pub(crate) const LACE_CF1_KERNEL_SIZE: usize = 16;
pub(crate) const LACE_CF1_LEFT_PADDING: usize = 8;
pub(crate) const LACE_CF1_FRAME_SIZE: usize = 80;
pub(crate) const LACE_CF1_OVERLAP_SIZE: usize = 40;
pub(crate) const LACE_CF1_IN_CHANNELS: usize = 1;
pub(crate) const LACE_CF1_OUT_CHANNELS: usize = 1;
pub(crate) const LACE_CF1_NORM_P: usize = 2;
pub(crate) const LACE_CF1_FEATURE_DIM: usize = 128;
pub(crate) const LACE_CF1_MAX_LAG: usize = 301;
pub(crate) const LACE_CF1_KERNEL_OUT_SIZE: usize = 16;
pub(crate) const LACE_CF1_GAIN_OUT_SIZE: usize = 1;
pub(crate) const LACE_CF1_GLOBAL_GAIN_OUT_SIZE: usize = 1;
pub(crate) const LACE_CF2_FILTER_GAIN_A: f32 = 0.690776;
pub(crate) const LACE_CF2_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const LACE_CF2_LOG_GAIN_LIMIT: f32 = 1.151293;
pub(crate) const LACE_CF2_KERNEL_SIZE: usize = 16;
pub(crate) const LACE_CF2_LEFT_PADDING: usize = 8;
pub(crate) const LACE_CF2_FRAME_SIZE: usize = 80;
pub(crate) const LACE_CF2_OVERLAP_SIZE: usize = 40;
pub(crate) const LACE_CF2_IN_CHANNELS: usize = 1;
pub(crate) const LACE_CF2_OUT_CHANNELS: usize = 1;
pub(crate) const LACE_CF2_NORM_P: usize = 2;
pub(crate) const LACE_CF2_FEATURE_DIM: usize = 128;
pub(crate) const LACE_CF2_MAX_LAG: usize = 301;
pub(crate) const LACE_CF2_KERNEL_OUT_SIZE: usize = 16;
pub(crate) const LACE_CF2_GAIN_OUT_SIZE: usize = 1;
pub(crate) const LACE_CF2_GLOBAL_GAIN_OUT_SIZE: usize = 1;
pub(crate) const LACE_AF1_FILTER_GAIN_A: f32 = 1.381551;
pub(crate) const LACE_AF1_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const LACE_AF1_SHAPE_GAIN: f32 = 1.000000;
pub(crate) const LACE_AF1_KERNEL_SIZE: usize = 16;
pub(crate) const LACE_AF1_FRAME_SIZE: usize = 80;
pub(crate) const LACE_AF1_LEFT_PADDING: usize = 15;
pub(crate) const LACE_AF1_OVERLAP_SIZE: usize = 40;
pub(crate) const LACE_AF1_IN_CHANNELS: usize = 1;
pub(crate) const LACE_AF1_OUT_CHANNELS: usize = 1;
pub(crate) const LACE_AF1_NORM_P: usize = 2;
pub(crate) const LACE_AF1_FEATURE_DIM: usize = 128;
pub(crate) const LACE_AF1_KERNEL_OUT_SIZE: usize = 16;
pub(crate) const LACE_AF1_GAIN_OUT_SIZE: usize = 1;
#[derive(Clone, Debug)]
pub(crate) struct LaceLayers {
    pub lace_pitch_embedding: OwnedLayer,
    pub lace_fnet_conv1: OwnedLayer,
    pub lace_fnet_conv2: OwnedLayer,
    pub lace_fnet_tconv: OwnedLayer,
    pub lace_fnet_gru_input: OwnedLayer,
    pub lace_fnet_gru_recurrent: OwnedLayer,
    pub lace_cf1_kernel: OwnedLayer,
    pub lace_cf1_gain: OwnedLayer,
    pub lace_cf1_global_gain: OwnedLayer,
    pub lace_cf2_kernel: OwnedLayer,
    pub lace_cf2_gain: OwnedLayer,
    pub lace_cf2_global_gain: OwnedLayer,
    pub lace_af1_kernel: OwnedLayer,
    pub lace_af1_gain: OwnedLayer,
}
impl LaceLayers {
    pub fn load(blob: &WeightBlob<'_>) -> Result<Self, WeightError> {
        Ok(Self {
            lace_pitch_embedding: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_pitch_embedding_bias"),
                        None,
                        None,
                        Some("lace_pitch_embedding_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 301,
                    outputs: 64,
                },
            )?,
            lace_fnet_conv1: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_fnet_conv1_bias"),
                        None,
                        None,
                        Some("lace_fnet_conv1_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 173,
                    outputs: 96,
                },
            )?,
            lace_fnet_conv2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_fnet_conv2_bias"),
                        Some("lace_fnet_conv2_subias"),
                        Some("lace_fnet_conv2_weights_int8"),
                        Some("lace_fnet_conv2_weights_float"),
                        None,
                        None,
                        Some("lace_fnet_conv2_scale"),
                    ],
                    inputs: 768,
                    outputs: 128,
                },
            )?,
            lace_fnet_tconv: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_fnet_tconv_bias"),
                        Some("lace_fnet_tconv_subias"),
                        Some("lace_fnet_tconv_weights_int8"),
                        Some("lace_fnet_tconv_weights_float"),
                        None,
                        None,
                        Some("lace_fnet_tconv_scale"),
                    ],
                    inputs: 128,
                    outputs: 512,
                },
            )?,
            lace_fnet_gru_input: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_fnet_gru_input_bias"),
                        Some("lace_fnet_gru_input_subias"),
                        Some("lace_fnet_gru_input_weights_int8"),
                        Some("lace_fnet_gru_input_weights_float"),
                        None,
                        None,
                        Some("lace_fnet_gru_input_scale"),
                    ],
                    inputs: 128,
                    outputs: 384,
                },
            )?,
            lace_fnet_gru_recurrent: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_fnet_gru_recurrent_bias"),
                        Some("lace_fnet_gru_recurrent_subias"),
                        Some("lace_fnet_gru_recurrent_weights_int8"),
                        Some("lace_fnet_gru_recurrent_weights_float"),
                        None,
                        None,
                        Some("lace_fnet_gru_recurrent_scale"),
                    ],
                    inputs: 128,
                    outputs: 384,
                },
            )?,
            lace_cf1_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_cf1_kernel_bias"),
                        Some("lace_cf1_kernel_subias"),
                        Some("lace_cf1_kernel_weights_int8"),
                        Some("lace_cf1_kernel_weights_float"),
                        None,
                        None,
                        Some("lace_cf1_kernel_scale"),
                    ],
                    inputs: 128,
                    outputs: 16,
                },
            )?,
            lace_cf1_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_cf1_gain_bias"),
                        None,
                        None,
                        Some("lace_cf1_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 128,
                    outputs: 1,
                },
            )?,
            lace_cf1_global_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_cf1_global_gain_bias"),
                        None,
                        None,
                        Some("lace_cf1_global_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 128,
                    outputs: 1,
                },
            )?,
            lace_cf2_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_cf2_kernel_bias"),
                        Some("lace_cf2_kernel_subias"),
                        Some("lace_cf2_kernel_weights_int8"),
                        Some("lace_cf2_kernel_weights_float"),
                        None,
                        None,
                        Some("lace_cf2_kernel_scale"),
                    ],
                    inputs: 128,
                    outputs: 16,
                },
            )?,
            lace_cf2_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_cf2_gain_bias"),
                        None,
                        None,
                        Some("lace_cf2_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 128,
                    outputs: 1,
                },
            )?,
            lace_cf2_global_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_cf2_global_gain_bias"),
                        None,
                        None,
                        Some("lace_cf2_global_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 128,
                    outputs: 1,
                },
            )?,
            lace_af1_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_af1_kernel_bias"),
                        Some("lace_af1_kernel_subias"),
                        Some("lace_af1_kernel_weights_int8"),
                        Some("lace_af1_kernel_weights_float"),
                        None,
                        None,
                        Some("lace_af1_kernel_scale"),
                    ],
                    inputs: 128,
                    outputs: 16,
                },
            )?,
            lace_af1_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("lace_af1_gain_bias"),
                        None,
                        None,
                        Some("lace_af1_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 128,
                    outputs: 1,
                },
            )?,
        })
    }
}
pub(crate) const NOLACE_PREEMPH: f32 = 0.85;
pub(crate) const NOLACE_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_OVERLAP_SIZE: usize = 40;
pub(crate) const NOLACE_NUM_FEATURES: usize = 93;
pub(crate) const NOLACE_PITCH_MAX: usize = 300;
pub(crate) const NOLACE_PITCH_EMBEDDING_DIM: usize = 64;
pub(crate) const NOLACE_NUMBITS_RANGE_LOW: usize = 50;
pub(crate) const NOLACE_NUMBITS_RANGE_HIGH: usize = 650;
pub(crate) const NOLACE_NUMBITS_EMBEDDING_DIM: usize = 8;
pub(crate) const NOLACE_COND_DIM: usize = 160;
pub(crate) const NOLACE_HIDDEN_FEATURE_DIM: usize = 96;
pub(crate) const NOLACE_NUMBITS_SCALE_0: f32 = 1.0357311964035034;
pub(crate) const NOLACE_NUMBITS_SCALE_1: f32 = 1.735559105873108;
pub(crate) const NOLACE_NUMBITS_SCALE_2: f32 = 3.6004557609558105;
pub(crate) const NOLACE_NUMBITS_SCALE_3: f32 = 4.552478313446045;
pub(crate) const NOLACE_NUMBITS_SCALE_4: f32 = 5.932559490203857;
pub(crate) const NOLACE_NUMBITS_SCALE_5: f32 = 7.176970481872559;
pub(crate) const NOLACE_NUMBITS_SCALE_6: f32 = 8.114998817443848;
pub(crate) const NOLACE_NUMBITS_SCALE_7: f32 = 8.77063274383545;
pub(crate) const NOLACE_PITCH_EMBEDDING_OUT_SIZE: usize = 64;
pub(crate) const NOLACE_FNET_CONV1_OUT_SIZE: usize = 96;
pub(crate) const NOLACE_FNET_CONV1_IN_SIZE: usize = 173;
pub(crate) const NOLACE_FNET_CONV1_STATE_SIZE: usize = (173 * (0));
pub(crate) const NOLACE_FNET_CONV1_DELAY: usize = 0;
pub(crate) const NOLACE_FNET_CONV2_OUT_SIZE: usize = 160;
pub(crate) const NOLACE_FNET_CONV2_IN_SIZE: usize = 384;
pub(crate) const NOLACE_FNET_CONV2_STATE_SIZE: usize = (384 * (1));
pub(crate) const NOLACE_FNET_CONV2_DELAY: usize = 0;
pub(crate) const NOLACE_FNET_TCONV_KERNEL_SIZE: usize = 4;
pub(crate) const NOLACE_FNET_TCONV_STRIDE: usize = 4;
pub(crate) const NOLACE_FNET_TCONV_IN_CHANNELS: usize = 160;
pub(crate) const NOLACE_FNET_TCONV_OUT_CHANNELS: usize = 160;
pub(crate) const NOLACE_FNET_GRU_OUT_SIZE: usize = 160;
pub(crate) const NOLACE_FNET_GRU_STATE_SIZE: usize = 160;
pub(crate) const NOLACE_CF1_FILTER_GAIN_A: f32 = 0.690776;
pub(crate) const NOLACE_CF1_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const NOLACE_CF1_LOG_GAIN_LIMIT: f32 = 1.151293;
pub(crate) const NOLACE_CF1_KERNEL_SIZE: usize = 16;
pub(crate) const NOLACE_CF1_LEFT_PADDING: usize = 8;
pub(crate) const NOLACE_CF1_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_CF1_OVERLAP_SIZE: usize = 40;
pub(crate) const NOLACE_CF1_IN_CHANNELS: usize = 1;
pub(crate) const NOLACE_CF1_OUT_CHANNELS: usize = 1;
pub(crate) const NOLACE_CF1_NORM_P: usize = 2;
pub(crate) const NOLACE_CF1_FEATURE_DIM: usize = 160;
pub(crate) const NOLACE_CF1_MAX_LAG: usize = 301;
pub(crate) const NOLACE_CF1_KERNEL_OUT_SIZE: usize = 16;
pub(crate) const NOLACE_CF1_GAIN_OUT_SIZE: usize = 1;
pub(crate) const NOLACE_CF1_GLOBAL_GAIN_OUT_SIZE: usize = 1;
pub(crate) const NOLACE_CF2_FILTER_GAIN_A: f32 = 0.690776;
pub(crate) const NOLACE_CF2_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const NOLACE_CF2_LOG_GAIN_LIMIT: f32 = 1.151293;
pub(crate) const NOLACE_CF2_KERNEL_SIZE: usize = 16;
pub(crate) const NOLACE_CF2_LEFT_PADDING: usize = 8;
pub(crate) const NOLACE_CF2_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_CF2_OVERLAP_SIZE: usize = 40;
pub(crate) const NOLACE_CF2_IN_CHANNELS: usize = 1;
pub(crate) const NOLACE_CF2_OUT_CHANNELS: usize = 1;
pub(crate) const NOLACE_CF2_NORM_P: usize = 2;
pub(crate) const NOLACE_CF2_FEATURE_DIM: usize = 160;
pub(crate) const NOLACE_CF2_MAX_LAG: usize = 301;
pub(crate) const NOLACE_CF2_KERNEL_OUT_SIZE: usize = 16;
pub(crate) const NOLACE_CF2_GAIN_OUT_SIZE: usize = 1;
pub(crate) const NOLACE_CF2_GLOBAL_GAIN_OUT_SIZE: usize = 1;
pub(crate) const NOLACE_AF1_FILTER_GAIN_A: f32 = 1.381551;
pub(crate) const NOLACE_AF1_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const NOLACE_AF1_SHAPE_GAIN: f32 = 1.000000;
pub(crate) const NOLACE_AF1_KERNEL_SIZE: usize = 16;
pub(crate) const NOLACE_AF1_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_AF1_LEFT_PADDING: usize = 15;
pub(crate) const NOLACE_AF1_OVERLAP_SIZE: usize = 40;
pub(crate) const NOLACE_AF1_IN_CHANNELS: usize = 1;
pub(crate) const NOLACE_AF1_OUT_CHANNELS: usize = 2;
pub(crate) const NOLACE_AF1_NORM_P: usize = 2;
pub(crate) const NOLACE_AF1_FEATURE_DIM: usize = 160;
pub(crate) const NOLACE_AF1_KERNEL_OUT_SIZE: usize = 32;
pub(crate) const NOLACE_AF1_GAIN_OUT_SIZE: usize = 2;
pub(crate) const NOLACE_TDSHAPE1_FEATURE_DIM: usize = 160;
pub(crate) const NOLACE_TDSHAPE1_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE1_AVG_POOL_K: usize = 4;
pub(crate) const NOLACE_TDSHAPE1_INNOVATE: usize = 0;
pub(crate) const NOLACE_TDSHAPE1_POOL_AFTER: usize = 0;
pub(crate) const NOLACE_TDSHAPE1_ALPHA1_F_OUT_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE1_ALPHA1_F_IN_SIZE: usize = 160;
pub(crate) const NOLACE_TDSHAPE1_ALPHA1_F_STATE_SIZE: usize = (160 * (1));
pub(crate) const NOLACE_TDSHAPE1_ALPHA1_F_DELAY: usize = 0;
pub(crate) const NOLACE_TDSHAPE1_ALPHA1_T_OUT_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE1_ALPHA1_T_IN_SIZE: usize = 21;
pub(crate) const NOLACE_TDSHAPE1_ALPHA1_T_STATE_SIZE: usize = (21 * (1));
pub(crate) const NOLACE_TDSHAPE1_ALPHA1_T_DELAY: usize = 0;
pub(crate) const NOLACE_TDSHAPE1_ALPHA2_OUT_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE1_ALPHA2_IN_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE1_ALPHA2_STATE_SIZE: usize = (80 * (1));
pub(crate) const NOLACE_TDSHAPE1_ALPHA2_DELAY: usize = 0;
pub(crate) const NOLACE_TDSHAPE2_FEATURE_DIM: usize = 160;
pub(crate) const NOLACE_TDSHAPE2_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE2_AVG_POOL_K: usize = 4;
pub(crate) const NOLACE_TDSHAPE2_INNOVATE: usize = 0;
pub(crate) const NOLACE_TDSHAPE2_POOL_AFTER: usize = 0;
pub(crate) const NOLACE_TDSHAPE2_ALPHA1_F_OUT_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE2_ALPHA1_F_IN_SIZE: usize = 160;
pub(crate) const NOLACE_TDSHAPE2_ALPHA1_F_STATE_SIZE: usize = (160 * (1));
pub(crate) const NOLACE_TDSHAPE2_ALPHA1_F_DELAY: usize = 0;
pub(crate) const NOLACE_TDSHAPE2_ALPHA1_T_OUT_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE2_ALPHA1_T_IN_SIZE: usize = 21;
pub(crate) const NOLACE_TDSHAPE2_ALPHA1_T_STATE_SIZE: usize = (21 * (1));
pub(crate) const NOLACE_TDSHAPE2_ALPHA1_T_DELAY: usize = 0;
pub(crate) const NOLACE_TDSHAPE2_ALPHA2_OUT_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE2_ALPHA2_IN_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE2_ALPHA2_STATE_SIZE: usize = (80 * (1));
pub(crate) const NOLACE_TDSHAPE2_ALPHA2_DELAY: usize = 0;
pub(crate) const NOLACE_TDSHAPE3_FEATURE_DIM: usize = 160;
pub(crate) const NOLACE_TDSHAPE3_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE3_AVG_POOL_K: usize = 4;
pub(crate) const NOLACE_TDSHAPE3_INNOVATE: usize = 0;
pub(crate) const NOLACE_TDSHAPE3_POOL_AFTER: usize = 0;
pub(crate) const NOLACE_TDSHAPE3_ALPHA1_F_OUT_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE3_ALPHA1_F_IN_SIZE: usize = 160;
pub(crate) const NOLACE_TDSHAPE3_ALPHA1_F_STATE_SIZE: usize = (160 * (1));
pub(crate) const NOLACE_TDSHAPE3_ALPHA1_F_DELAY: usize = 0;
pub(crate) const NOLACE_TDSHAPE3_ALPHA1_T_OUT_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE3_ALPHA1_T_IN_SIZE: usize = 21;
pub(crate) const NOLACE_TDSHAPE3_ALPHA1_T_STATE_SIZE: usize = (21 * (1));
pub(crate) const NOLACE_TDSHAPE3_ALPHA1_T_DELAY: usize = 0;
pub(crate) const NOLACE_TDSHAPE3_ALPHA2_OUT_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE3_ALPHA2_IN_SIZE: usize = 80;
pub(crate) const NOLACE_TDSHAPE3_ALPHA2_STATE_SIZE: usize = (80 * (1));
pub(crate) const NOLACE_TDSHAPE3_ALPHA2_DELAY: usize = 0;
pub(crate) const NOLACE_AF2_FILTER_GAIN_A: f32 = 1.381551;
pub(crate) const NOLACE_AF2_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const NOLACE_AF2_SHAPE_GAIN: f32 = 1.000000;
pub(crate) const NOLACE_AF2_KERNEL_SIZE: usize = 16;
pub(crate) const NOLACE_AF2_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_AF2_LEFT_PADDING: usize = 15;
pub(crate) const NOLACE_AF2_OVERLAP_SIZE: usize = 40;
pub(crate) const NOLACE_AF2_IN_CHANNELS: usize = 2;
pub(crate) const NOLACE_AF2_OUT_CHANNELS: usize = 2;
pub(crate) const NOLACE_AF2_NORM_P: usize = 2;
pub(crate) const NOLACE_AF2_FEATURE_DIM: usize = 160;
pub(crate) const NOLACE_AF2_KERNEL_OUT_SIZE: usize = 64;
pub(crate) const NOLACE_AF2_GAIN_OUT_SIZE: usize = 2;
pub(crate) const NOLACE_AF3_FILTER_GAIN_A: f32 = 1.381551;
pub(crate) const NOLACE_AF3_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const NOLACE_AF3_SHAPE_GAIN: f32 = 1.000000;
pub(crate) const NOLACE_AF3_KERNEL_SIZE: usize = 16;
pub(crate) const NOLACE_AF3_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_AF3_LEFT_PADDING: usize = 15;
pub(crate) const NOLACE_AF3_OVERLAP_SIZE: usize = 40;
pub(crate) const NOLACE_AF3_IN_CHANNELS: usize = 2;
pub(crate) const NOLACE_AF3_OUT_CHANNELS: usize = 2;
pub(crate) const NOLACE_AF3_NORM_P: usize = 2;
pub(crate) const NOLACE_AF3_FEATURE_DIM: usize = 160;
pub(crate) const NOLACE_AF3_KERNEL_OUT_SIZE: usize = 64;
pub(crate) const NOLACE_AF3_GAIN_OUT_SIZE: usize = 2;
pub(crate) const NOLACE_AF4_FILTER_GAIN_A: f32 = 1.381551;
pub(crate) const NOLACE_AF4_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const NOLACE_AF4_SHAPE_GAIN: f32 = 1.000000;
pub(crate) const NOLACE_AF4_KERNEL_SIZE: usize = 16;
pub(crate) const NOLACE_AF4_FRAME_SIZE: usize = 80;
pub(crate) const NOLACE_AF4_LEFT_PADDING: usize = 15;
pub(crate) const NOLACE_AF4_OVERLAP_SIZE: usize = 40;
pub(crate) const NOLACE_AF4_IN_CHANNELS: usize = 2;
pub(crate) const NOLACE_AF4_OUT_CHANNELS: usize = 1;
pub(crate) const NOLACE_AF4_NORM_P: usize = 2;
pub(crate) const NOLACE_AF4_FEATURE_DIM: usize = 160;
pub(crate) const NOLACE_AF4_KERNEL_OUT_SIZE: usize = 32;
pub(crate) const NOLACE_AF4_GAIN_OUT_SIZE: usize = 1;
pub(crate) const NOLACE_POST_CF1_OUT_SIZE: usize = 160;
pub(crate) const NOLACE_POST_CF1_IN_SIZE: usize = 160;
pub(crate) const NOLACE_POST_CF1_STATE_SIZE: usize = (160 * (1));
pub(crate) const NOLACE_POST_CF1_DELAY: usize = 0;
pub(crate) const NOLACE_POST_CF2_OUT_SIZE: usize = 160;
pub(crate) const NOLACE_POST_CF2_IN_SIZE: usize = 160;
pub(crate) const NOLACE_POST_CF2_STATE_SIZE: usize = (160 * (1));
pub(crate) const NOLACE_POST_CF2_DELAY: usize = 0;
pub(crate) const NOLACE_POST_AF1_OUT_SIZE: usize = 160;
pub(crate) const NOLACE_POST_AF1_IN_SIZE: usize = 160;
pub(crate) const NOLACE_POST_AF1_STATE_SIZE: usize = (160 * (1));
pub(crate) const NOLACE_POST_AF1_DELAY: usize = 0;
pub(crate) const NOLACE_POST_AF2_OUT_SIZE: usize = 160;
pub(crate) const NOLACE_POST_AF2_IN_SIZE: usize = 160;
pub(crate) const NOLACE_POST_AF2_STATE_SIZE: usize = (160 * (1));
pub(crate) const NOLACE_POST_AF2_DELAY: usize = 0;
pub(crate) const NOLACE_POST_AF3_OUT_SIZE: usize = 160;
pub(crate) const NOLACE_POST_AF3_IN_SIZE: usize = 160;
pub(crate) const NOLACE_POST_AF3_STATE_SIZE: usize = (160 * (1));
pub(crate) const NOLACE_POST_AF3_DELAY: usize = 0;
#[derive(Clone, Debug)]
pub(crate) struct NoLaceLayers {
    pub nolace_pitch_embedding: OwnedLayer,
    pub nolace_fnet_conv1: OwnedLayer,
    pub nolace_fnet_conv2: OwnedLayer,
    pub nolace_fnet_tconv: OwnedLayer,
    pub nolace_fnet_gru_input: OwnedLayer,
    pub nolace_fnet_gru_recurrent: OwnedLayer,
    pub nolace_cf1_kernel: OwnedLayer,
    pub nolace_cf1_gain: OwnedLayer,
    pub nolace_cf1_global_gain: OwnedLayer,
    pub nolace_cf2_kernel: OwnedLayer,
    pub nolace_cf2_gain: OwnedLayer,
    pub nolace_cf2_global_gain: OwnedLayer,
    pub nolace_af1_kernel: OwnedLayer,
    pub nolace_af1_gain: OwnedLayer,
    pub nolace_tdshape1_alpha1_f: OwnedLayer,
    pub nolace_tdshape1_alpha1_t: OwnedLayer,
    pub nolace_tdshape1_alpha2: OwnedLayer,
    pub nolace_tdshape2_alpha1_f: OwnedLayer,
    pub nolace_tdshape2_alpha1_t: OwnedLayer,
    pub nolace_tdshape2_alpha2: OwnedLayer,
    pub nolace_tdshape3_alpha1_f: OwnedLayer,
    pub nolace_tdshape3_alpha1_t: OwnedLayer,
    pub nolace_tdshape3_alpha2: OwnedLayer,
    pub nolace_af2_kernel: OwnedLayer,
    pub nolace_af2_gain: OwnedLayer,
    pub nolace_af3_kernel: OwnedLayer,
    pub nolace_af3_gain: OwnedLayer,
    pub nolace_af4_kernel: OwnedLayer,
    pub nolace_af4_gain: OwnedLayer,
    pub nolace_post_cf1: OwnedLayer,
    pub nolace_post_cf2: OwnedLayer,
    pub nolace_post_af1: OwnedLayer,
    pub nolace_post_af2: OwnedLayer,
    pub nolace_post_af3: OwnedLayer,
}
impl NoLaceLayers {
    pub fn load(blob: &WeightBlob<'_>) -> Result<Self, WeightError> {
        Ok(Self {
            nolace_pitch_embedding: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_pitch_embedding_bias"),
                        None,
                        None,
                        Some("nolace_pitch_embedding_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 301,
                    outputs: 64,
                },
            )?,
            nolace_fnet_conv1: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_fnet_conv1_bias"),
                        None,
                        None,
                        Some("nolace_fnet_conv1_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 173,
                    outputs: 96,
                },
            )?,
            nolace_fnet_conv2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_fnet_conv2_bias"),
                        Some("nolace_fnet_conv2_subias"),
                        Some("nolace_fnet_conv2_weights_int8"),
                        Some("nolace_fnet_conv2_weights_float"),
                        None,
                        None,
                        Some("nolace_fnet_conv2_scale"),
                    ],
                    inputs: 768,
                    outputs: 160,
                },
            )?,
            nolace_fnet_tconv: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_fnet_tconv_bias"),
                        Some("nolace_fnet_tconv_subias"),
                        Some("nolace_fnet_tconv_weights_int8"),
                        Some("nolace_fnet_tconv_weights_float"),
                        None,
                        None,
                        Some("nolace_fnet_tconv_scale"),
                    ],
                    inputs: 160,
                    outputs: 640,
                },
            )?,
            nolace_fnet_gru_input: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_fnet_gru_input_bias"),
                        Some("nolace_fnet_gru_input_subias"),
                        Some("nolace_fnet_gru_input_weights_int8"),
                        Some("nolace_fnet_gru_input_weights_float"),
                        None,
                        None,
                        Some("nolace_fnet_gru_input_scale"),
                    ],
                    inputs: 160,
                    outputs: 480,
                },
            )?,
            nolace_fnet_gru_recurrent: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_fnet_gru_recurrent_bias"),
                        Some("nolace_fnet_gru_recurrent_subias"),
                        Some("nolace_fnet_gru_recurrent_weights_int8"),
                        Some("nolace_fnet_gru_recurrent_weights_float"),
                        None,
                        None,
                        Some("nolace_fnet_gru_recurrent_scale"),
                    ],
                    inputs: 160,
                    outputs: 480,
                },
            )?,
            nolace_cf1_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_cf1_kernel_bias"),
                        Some("nolace_cf1_kernel_subias"),
                        Some("nolace_cf1_kernel_weights_int8"),
                        Some("nolace_cf1_kernel_weights_float"),
                        None,
                        None,
                        Some("nolace_cf1_kernel_scale"),
                    ],
                    inputs: 160,
                    outputs: 16,
                },
            )?,
            nolace_cf1_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_cf1_gain_bias"),
                        None,
                        None,
                        Some("nolace_cf1_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 1,
                },
            )?,
            nolace_cf1_global_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_cf1_global_gain_bias"),
                        None,
                        None,
                        Some("nolace_cf1_global_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 1,
                },
            )?,
            nolace_cf2_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_cf2_kernel_bias"),
                        Some("nolace_cf2_kernel_subias"),
                        Some("nolace_cf2_kernel_weights_int8"),
                        Some("nolace_cf2_kernel_weights_float"),
                        None,
                        None,
                        Some("nolace_cf2_kernel_scale"),
                    ],
                    inputs: 160,
                    outputs: 16,
                },
            )?,
            nolace_cf2_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_cf2_gain_bias"),
                        None,
                        None,
                        Some("nolace_cf2_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 1,
                },
            )?,
            nolace_cf2_global_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_cf2_global_gain_bias"),
                        None,
                        None,
                        Some("nolace_cf2_global_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 1,
                },
            )?,
            nolace_af1_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_af1_kernel_bias"),
                        Some("nolace_af1_kernel_subias"),
                        Some("nolace_af1_kernel_weights_int8"),
                        Some("nolace_af1_kernel_weights_float"),
                        None,
                        None,
                        Some("nolace_af1_kernel_scale"),
                    ],
                    inputs: 160,
                    outputs: 32,
                },
            )?,
            nolace_af1_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_af1_gain_bias"),
                        None,
                        None,
                        Some("nolace_af1_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 2,
                },
            )?,
            nolace_tdshape1_alpha1_f: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_tdshape1_alpha1_f_bias"),
                        Some("nolace_tdshape1_alpha1_f_subias"),
                        Some("nolace_tdshape1_alpha1_f_weights_int8"),
                        Some("nolace_tdshape1_alpha1_f_weights_float"),
                        None,
                        None,
                        Some("nolace_tdshape1_alpha1_f_scale"),
                    ],
                    inputs: 320,
                    outputs: 80,
                },
            )?,
            nolace_tdshape1_alpha1_t: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_tdshape1_alpha1_t_bias"),
                        None,
                        None,
                        Some("nolace_tdshape1_alpha1_t_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 42,
                    outputs: 80,
                },
            )?,
            nolace_tdshape1_alpha2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_tdshape1_alpha2_bias"),
                        None,
                        None,
                        Some("nolace_tdshape1_alpha2_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 80,
                },
            )?,
            nolace_tdshape2_alpha1_f: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_tdshape2_alpha1_f_bias"),
                        Some("nolace_tdshape2_alpha1_f_subias"),
                        Some("nolace_tdshape2_alpha1_f_weights_int8"),
                        Some("nolace_tdshape2_alpha1_f_weights_float"),
                        None,
                        None,
                        Some("nolace_tdshape2_alpha1_f_scale"),
                    ],
                    inputs: 320,
                    outputs: 80,
                },
            )?,
            nolace_tdshape2_alpha1_t: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_tdshape2_alpha1_t_bias"),
                        None,
                        None,
                        Some("nolace_tdshape2_alpha1_t_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 42,
                    outputs: 80,
                },
            )?,
            nolace_tdshape2_alpha2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_tdshape2_alpha2_bias"),
                        None,
                        None,
                        Some("nolace_tdshape2_alpha2_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 80,
                },
            )?,
            nolace_tdshape3_alpha1_f: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_tdshape3_alpha1_f_bias"),
                        Some("nolace_tdshape3_alpha1_f_subias"),
                        Some("nolace_tdshape3_alpha1_f_weights_int8"),
                        Some("nolace_tdshape3_alpha1_f_weights_float"),
                        None,
                        None,
                        Some("nolace_tdshape3_alpha1_f_scale"),
                    ],
                    inputs: 320,
                    outputs: 80,
                },
            )?,
            nolace_tdshape3_alpha1_t: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_tdshape3_alpha1_t_bias"),
                        None,
                        None,
                        Some("nolace_tdshape3_alpha1_t_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 42,
                    outputs: 80,
                },
            )?,
            nolace_tdshape3_alpha2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_tdshape3_alpha2_bias"),
                        None,
                        None,
                        Some("nolace_tdshape3_alpha2_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 80,
                },
            )?,
            nolace_af2_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_af2_kernel_bias"),
                        Some("nolace_af2_kernel_subias"),
                        Some("nolace_af2_kernel_weights_int8"),
                        Some("nolace_af2_kernel_weights_float"),
                        None,
                        None,
                        Some("nolace_af2_kernel_scale"),
                    ],
                    inputs: 160,
                    outputs: 64,
                },
            )?,
            nolace_af2_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_af2_gain_bias"),
                        None,
                        None,
                        Some("nolace_af2_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 2,
                },
            )?,
            nolace_af3_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_af3_kernel_bias"),
                        Some("nolace_af3_kernel_subias"),
                        Some("nolace_af3_kernel_weights_int8"),
                        Some("nolace_af3_kernel_weights_float"),
                        None,
                        None,
                        Some("nolace_af3_kernel_scale"),
                    ],
                    inputs: 160,
                    outputs: 64,
                },
            )?,
            nolace_af3_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_af3_gain_bias"),
                        None,
                        None,
                        Some("nolace_af3_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 2,
                },
            )?,
            nolace_af4_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_af4_kernel_bias"),
                        Some("nolace_af4_kernel_subias"),
                        Some("nolace_af4_kernel_weights_int8"),
                        Some("nolace_af4_kernel_weights_float"),
                        None,
                        None,
                        Some("nolace_af4_kernel_scale"),
                    ],
                    inputs: 160,
                    outputs: 32,
                },
            )?,
            nolace_af4_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_af4_gain_bias"),
                        None,
                        None,
                        Some("nolace_af4_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 1,
                },
            )?,
            nolace_post_cf1: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_post_cf1_bias"),
                        Some("nolace_post_cf1_subias"),
                        Some("nolace_post_cf1_weights_int8"),
                        Some("nolace_post_cf1_weights_float"),
                        None,
                        None,
                        Some("nolace_post_cf1_scale"),
                    ],
                    inputs: 320,
                    outputs: 160,
                },
            )?,
            nolace_post_cf2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_post_cf2_bias"),
                        Some("nolace_post_cf2_subias"),
                        Some("nolace_post_cf2_weights_int8"),
                        Some("nolace_post_cf2_weights_float"),
                        None,
                        None,
                        Some("nolace_post_cf2_scale"),
                    ],
                    inputs: 320,
                    outputs: 160,
                },
            )?,
            nolace_post_af1: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_post_af1_bias"),
                        Some("nolace_post_af1_subias"),
                        Some("nolace_post_af1_weights_int8"),
                        Some("nolace_post_af1_weights_float"),
                        None,
                        None,
                        Some("nolace_post_af1_scale"),
                    ],
                    inputs: 320,
                    outputs: 160,
                },
            )?,
            nolace_post_af2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_post_af2_bias"),
                        Some("nolace_post_af2_subias"),
                        Some("nolace_post_af2_weights_int8"),
                        Some("nolace_post_af2_weights_float"),
                        None,
                        None,
                        Some("nolace_post_af2_scale"),
                    ],
                    inputs: 320,
                    outputs: 160,
                },
            )?,
            nolace_post_af3: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("nolace_post_af3_bias"),
                        Some("nolace_post_af3_subias"),
                        Some("nolace_post_af3_weights_int8"),
                        Some("nolace_post_af3_weights_float"),
                        None,
                        None,
                        Some("nolace_post_af3_scale"),
                    ],
                    inputs: 320,
                    outputs: 160,
                },
            )?,
        })
    }
}
pub(crate) const BBWENET_FEATURE_DIM: usize = 114;
pub(crate) const BBWENET_FRAME_SIZE16: usize = 80;
pub(crate) const BBWENET_COND_DIM: usize = 128;
pub(crate) const BBWENET_FNET_CONV1_OUT_SIZE: usize = 128;
pub(crate) const BBWENET_FNET_CONV1_IN_SIZE: usize = 114;
pub(crate) const BBWENET_FNET_CONV1_STATE_SIZE: usize = (114 * (2));
pub(crate) const BBWENET_FNET_CONV2_OUT_SIZE: usize = 128;
pub(crate) const BBWENET_FNET_CONV2_IN_SIZE: usize = 128;
pub(crate) const BBWENET_FNET_CONV2_STATE_SIZE: usize = (128 * (2));
pub(crate) const BBWENET_FNET_GRU_OUT_SIZE: usize = 128;
pub(crate) const BBWENET_FNET_GRU_STATE_SIZE: usize = 128;
pub(crate) const BBWENET_FNET_TCONV_KERNEL_SIZE: usize = 2;
pub(crate) const BBWENET_FNET_TCONV_STRIDE: usize = 2;
pub(crate) const BBWENET_FNET_TCONV_IN_CHANNELS: usize = 128;
pub(crate) const BBWENET_FNET_TCONV_OUT_CHANNELS: usize = 128;
pub(crate) const BBWENET_TDSHAPE1_FEATURE_DIM: usize = 128;
pub(crate) const BBWENET_TDSHAPE1_FRAME_SIZE: usize = 160;
pub(crate) const BBWENET_TDSHAPE1_AVG_POOL_K: usize = 8;
pub(crate) const BBWENET_TDSHAPE1_INNOVATE: usize = 0;
pub(crate) const BBWENET_TDSHAPE1_POOL_AFTER: usize = 0;
pub(crate) const BBWENET_TDSHAPE1_INTERPOLATE_K: usize = 2;
pub(crate) const BBWENET_TDSHAPE1_ALPHA1_F_OUT_SIZE: usize = 80;
pub(crate) const BBWENET_TDSHAPE1_ALPHA1_F_IN_SIZE: usize = 128;
pub(crate) const BBWENET_TDSHAPE1_ALPHA1_F_STATE_SIZE: usize = (128 * (1));
pub(crate) const BBWENET_TDSHAPE1_ALPHA1_T_OUT_SIZE: usize = 80;
pub(crate) const BBWENET_TDSHAPE1_ALPHA1_T_IN_SIZE: usize = 21;
pub(crate) const BBWENET_TDSHAPE1_ALPHA1_T_STATE_SIZE: usize = (21 * (1));
pub(crate) const BBWENET_TDSHAPE1_ALPHA2_OUT_SIZE: usize = 80;
pub(crate) const BBWENET_TDSHAPE1_ALPHA2_IN_SIZE: usize = 80;
pub(crate) const BBWENET_TDSHAPE1_ALPHA2_STATE_SIZE: usize = (80 * (1));
pub(crate) const BBWENET_TDSHAPE2_FEATURE_DIM: usize = 128;
pub(crate) const BBWENET_TDSHAPE2_FRAME_SIZE: usize = 240;
pub(crate) const BBWENET_TDSHAPE2_AVG_POOL_K: usize = 12;
pub(crate) const BBWENET_TDSHAPE2_INNOVATE: usize = 0;
pub(crate) const BBWENET_TDSHAPE2_POOL_AFTER: usize = 0;
pub(crate) const BBWENET_TDSHAPE2_INTERPOLATE_K: usize = 2;
pub(crate) const BBWENET_TDSHAPE2_ALPHA1_F_OUT_SIZE: usize = 120;
pub(crate) const BBWENET_TDSHAPE2_ALPHA1_F_IN_SIZE: usize = 128;
pub(crate) const BBWENET_TDSHAPE2_ALPHA1_F_STATE_SIZE: usize = (128 * (1));
pub(crate) const BBWENET_TDSHAPE2_ALPHA1_T_OUT_SIZE: usize = 120;
pub(crate) const BBWENET_TDSHAPE2_ALPHA1_T_IN_SIZE: usize = 21;
pub(crate) const BBWENET_TDSHAPE2_ALPHA1_T_STATE_SIZE: usize = (21 * (1));
pub(crate) const BBWENET_TDSHAPE2_ALPHA2_OUT_SIZE: usize = 120;
pub(crate) const BBWENET_TDSHAPE2_ALPHA2_IN_SIZE: usize = 120;
pub(crate) const BBWENET_TDSHAPE2_ALPHA2_STATE_SIZE: usize = (120 * (1));
pub(crate) const BBWENET_AF1_FILTER_GAIN_A: f32 = 1.381551;
pub(crate) const BBWENET_AF1_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const BBWENET_AF1_SHAPE_GAIN: f32 = 1.000000;
pub(crate) const BBWENET_AF1_KERNEL_SIZE: usize = 16;
pub(crate) const BBWENET_AF1_FRAME_SIZE: usize = 80;
pub(crate) const BBWENET_AF1_LEFT_PADDING: usize = 15;
pub(crate) const BBWENET_AF1_OVERLAP_SIZE: usize = 40;
pub(crate) const BBWENET_AF1_IN_CHANNELS: usize = 1;
pub(crate) const BBWENET_AF1_OUT_CHANNELS: usize = 3;
pub(crate) const BBWENET_AF1_NORM_P: usize = 2;
pub(crate) const BBWENET_AF1_FEATURE_DIM: usize = 128;
pub(crate) const BBWENET_AF1_KERNEL_OUT_SIZE: usize = 48;
pub(crate) const BBWENET_AF1_GAIN_OUT_SIZE: usize = 3;
pub(crate) const BBWENET_AF2_FILTER_GAIN_A: f32 = 1.381551;
pub(crate) const BBWENET_AF2_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const BBWENET_AF2_SHAPE_GAIN: f32 = 1.000000;
pub(crate) const BBWENET_AF2_KERNEL_SIZE: usize = 32;
pub(crate) const BBWENET_AF2_FRAME_SIZE: usize = 160;
pub(crate) const BBWENET_AF2_LEFT_PADDING: usize = 31;
pub(crate) const BBWENET_AF2_OVERLAP_SIZE: usize = 80;
pub(crate) const BBWENET_AF2_IN_CHANNELS: usize = 3;
pub(crate) const BBWENET_AF2_OUT_CHANNELS: usize = 3;
pub(crate) const BBWENET_AF2_NORM_P: usize = 2;
pub(crate) const BBWENET_AF2_FEATURE_DIM: usize = 128;
pub(crate) const BBWENET_AF2_KERNEL_OUT_SIZE: usize = 288;
pub(crate) const BBWENET_AF2_GAIN_OUT_SIZE: usize = 3;
pub(crate) const BBWENET_AF3_FILTER_GAIN_A: f32 = 1.381551;
pub(crate) const BBWENET_AF3_FILTER_GAIN_B: f32 = 0.000000;
pub(crate) const BBWENET_AF3_SHAPE_GAIN: f32 = 1.000000;
pub(crate) const BBWENET_AF3_KERNEL_SIZE: usize = 16;
pub(crate) const BBWENET_AF3_FRAME_SIZE: usize = 240;
pub(crate) const BBWENET_AF3_LEFT_PADDING: usize = 15;
pub(crate) const BBWENET_AF3_OVERLAP_SIZE: usize = 120;
pub(crate) const BBWENET_AF3_IN_CHANNELS: usize = 3;
pub(crate) const BBWENET_AF3_OUT_CHANNELS: usize = 1;
pub(crate) const BBWENET_AF3_NORM_P: usize = 2;
pub(crate) const BBWENET_AF3_FEATURE_DIM: usize = 128;
pub(crate) const BBWENET_AF3_KERNEL_OUT_SIZE: usize = 48;
pub(crate) const BBWENET_AF3_GAIN_OUT_SIZE: usize = 1;
#[derive(Clone, Debug)]
pub(crate) struct BbweLayers {
    pub bbwenet_fnet_conv1: OwnedLayer,
    pub bbwenet_fnet_conv2: OwnedLayer,
    pub bbwenet_fnet_gru_input: OwnedLayer,
    pub bbwenet_fnet_gru_recurrent: OwnedLayer,
    pub bbwenet_fnet_tconv: OwnedLayer,
    pub bbwenet_tdshape1_alpha1_f: OwnedLayer,
    pub bbwenet_tdshape1_alpha1_t: OwnedLayer,
    pub bbwenet_tdshape1_alpha2: OwnedLayer,
    pub bbwenet_tdshape2_alpha1_f: OwnedLayer,
    pub bbwenet_tdshape2_alpha1_t: OwnedLayer,
    pub bbwenet_tdshape2_alpha2: OwnedLayer,
    pub bbwenet_af1_kernel: OwnedLayer,
    pub bbwenet_af1_gain: OwnedLayer,
    pub bbwenet_af2_kernel: OwnedLayer,
    pub bbwenet_af2_gain: OwnedLayer,
    pub bbwenet_af3_kernel: OwnedLayer,
    pub bbwenet_af3_gain: OwnedLayer,
}
impl BbweLayers {
    pub fn load(blob: &WeightBlob<'_>) -> Result<Self, WeightError> {
        Ok(Self {
            bbwenet_fnet_conv1: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_fnet_conv1_bias"),
                        None,
                        None,
                        Some("bbwenet_fnet_conv1_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 342,
                    outputs: 128,
                },
            )?,
            bbwenet_fnet_conv2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_fnet_conv2_bias"),
                        Some("bbwenet_fnet_conv2_subias"),
                        Some("bbwenet_fnet_conv2_weights_int8"),
                        Some("bbwenet_fnet_conv2_weights_float"),
                        None,
                        None,
                        Some("bbwenet_fnet_conv2_scale"),
                    ],
                    inputs: 384,
                    outputs: 128,
                },
            )?,
            bbwenet_fnet_gru_input: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_fnet_gru_input_bias"),
                        Some("bbwenet_fnet_gru_input_subias"),
                        Some("bbwenet_fnet_gru_input_weights_int8"),
                        Some("bbwenet_fnet_gru_input_weights_float"),
                        None,
                        None,
                        Some("bbwenet_fnet_gru_input_scale"),
                    ],
                    inputs: 128,
                    outputs: 384,
                },
            )?,
            bbwenet_fnet_gru_recurrent: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_fnet_gru_recurrent_bias"),
                        Some("bbwenet_fnet_gru_recurrent_subias"),
                        Some("bbwenet_fnet_gru_recurrent_weights_int8"),
                        Some("bbwenet_fnet_gru_recurrent_weights_float"),
                        None,
                        None,
                        Some("bbwenet_fnet_gru_recurrent_scale"),
                    ],
                    inputs: 128,
                    outputs: 384,
                },
            )?,
            bbwenet_fnet_tconv: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_fnet_tconv_bias"),
                        Some("bbwenet_fnet_tconv_subias"),
                        Some("bbwenet_fnet_tconv_weights_int8"),
                        Some("bbwenet_fnet_tconv_weights_float"),
                        None,
                        None,
                        Some("bbwenet_fnet_tconv_scale"),
                    ],
                    inputs: 128,
                    outputs: 256,
                },
            )?,
            bbwenet_tdshape1_alpha1_f: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_tdshape1_alpha1_f_bias"),
                        Some("bbwenet_tdshape1_alpha1_f_subias"),
                        Some("bbwenet_tdshape1_alpha1_f_weights_int8"),
                        Some("bbwenet_tdshape1_alpha1_f_weights_float"),
                        None,
                        None,
                        Some("bbwenet_tdshape1_alpha1_f_scale"),
                    ],
                    inputs: 256,
                    outputs: 80,
                },
            )?,
            bbwenet_tdshape1_alpha1_t: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_tdshape1_alpha1_t_bias"),
                        None,
                        None,
                        Some("bbwenet_tdshape1_alpha1_t_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 42,
                    outputs: 80,
                },
            )?,
            bbwenet_tdshape1_alpha2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_tdshape1_alpha2_bias"),
                        None,
                        None,
                        Some("bbwenet_tdshape1_alpha2_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 160,
                    outputs: 80,
                },
            )?,
            bbwenet_tdshape2_alpha1_f: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_tdshape2_alpha1_f_bias"),
                        Some("bbwenet_tdshape2_alpha1_f_subias"),
                        Some("bbwenet_tdshape2_alpha1_f_weights_int8"),
                        Some("bbwenet_tdshape2_alpha1_f_weights_float"),
                        None,
                        None,
                        Some("bbwenet_tdshape2_alpha1_f_scale"),
                    ],
                    inputs: 256,
                    outputs: 120,
                },
            )?,
            bbwenet_tdshape2_alpha1_t: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_tdshape2_alpha1_t_bias"),
                        None,
                        None,
                        Some("bbwenet_tdshape2_alpha1_t_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 42,
                    outputs: 120,
                },
            )?,
            bbwenet_tdshape2_alpha2: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_tdshape2_alpha2_bias"),
                        None,
                        None,
                        Some("bbwenet_tdshape2_alpha2_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 240,
                    outputs: 120,
                },
            )?,
            bbwenet_af1_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_af1_kernel_bias"),
                        Some("bbwenet_af1_kernel_subias"),
                        Some("bbwenet_af1_kernel_weights_int8"),
                        Some("bbwenet_af1_kernel_weights_float"),
                        None,
                        None,
                        Some("bbwenet_af1_kernel_scale"),
                    ],
                    inputs: 128,
                    outputs: 48,
                },
            )?,
            bbwenet_af1_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_af1_gain_bias"),
                        None,
                        None,
                        Some("bbwenet_af1_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 128,
                    outputs: 3,
                },
            )?,
            bbwenet_af2_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_af2_kernel_bias"),
                        Some("bbwenet_af2_kernel_subias"),
                        Some("bbwenet_af2_kernel_weights_int8"),
                        Some("bbwenet_af2_kernel_weights_float"),
                        None,
                        None,
                        Some("bbwenet_af2_kernel_scale"),
                    ],
                    inputs: 128,
                    outputs: 288,
                },
            )?,
            bbwenet_af2_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_af2_gain_bias"),
                        None,
                        None,
                        Some("bbwenet_af2_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 128,
                    outputs: 3,
                },
            )?,
            bbwenet_af3_kernel: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_af3_kernel_bias"),
                        Some("bbwenet_af3_kernel_subias"),
                        Some("bbwenet_af3_kernel_weights_int8"),
                        Some("bbwenet_af3_kernel_weights_float"),
                        None,
                        None,
                        Some("bbwenet_af3_kernel_scale"),
                    ],
                    inputs: 128,
                    outputs: 48,
                },
            )?,
            bbwenet_af3_gain: OwnedLayer::load(
                blob,
                LayerSpec {
                    names: [
                        Some("bbwenet_af3_gain_bias"),
                        None,
                        None,
                        Some("bbwenet_af3_gain_weights_float"),
                        None,
                        None,
                        None,
                    ],
                    inputs: 128,
                    outputs: 1,
                },
            )?,
        })
    }
}
