#!/usr/bin/env python3
"""Extract the pinned scalar PFA permutation tables without recomputing them."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
source = (ROOT / 'celt/celt_tx_tables.c').read_text()
output = ('// Copyright (c) 2026 Lynne. BSD-3-Clause; see LICENSE.\n'
          '// Generated by tools/reference/extract_pfa_tables.py from the pinned C tables.\n')
for length in [60, 120, 240, 480, 960]:
    for family, size in [('mdct', 2 * length), ('pfa', length)]:
        name = f'celt_tx_{family}_map_{size}'
        body = re.search(r'const opus_int16 ' + name + r'\[\d+\] = \{(.*?)\};', source, re.S).group(1)
        values = [int(value) for value in re.findall(r'\d+', body)]
        if family == 'mdct':
            values = values[length:]
        assert len(values) == length
        if length == 960:
            output += '#[cfg(feature = "enable_qext")]\n'
        output += f'pub(super) const {family.upper()}_{length}: [usize; {length}] = [\n'
        for index in range(0, length, 16):
            output += '    ' + ', '.join(map(str, values[index:index + 16])) + ',\n'
        output += '];\n'
(ROOT / 'rust/src/celt/pfa_tables.rs').write_text(output)
