#!/usr/bin/env python3
"""Generate compact SILK packet/range fixtures using only the pinned C codec."""
import argparse
from pathlib import Path
import os
import tempfile
from compare_codec import ROOT, cases, pcm_input, run


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=("float", "fixed", "fixed-res24"), default="float")
    args = parser.parse_args()
    suffix = "" if args.profile == "float" else "-" + args.profile
    configurations = []
    for rate, channels, duration, mode, pattern in cases(False):
        if mode == "silk":
            for fec in (0, 1):
                configurations.append((rate, channels, duration, 10, 0, fec, 15 if fec else 0, pattern, 3))
    for fec in (0, 1):
        for complexity in range(11):
            for vbr in (0, 1):
                for rate in (8000, 12000, 16000):
                    for channels in (1, 2):
                        configurations.append((rate, channels, 20000, complexity, vbr, fec, 15 if fec else 0, "mixed", 5))
    records = ["# Generated by generate_silk_encoder_vectors.py from C revision 503d81b138d76621aae4b12786e90de48aa8db3a."]
    with tempfile.TemporaryDirectory(prefix="opus-silk-vectors-") as directory:
        pcm = Path(directory) / "input.pcm"
        for configuration in configurations:
            rate, channels, duration, complexity, vbr, fec, loss, pattern, frames = configuration
            size = rate * duration // 1000000
            os.environ.update(OPUS_ORACLE_COMPLEXITY=str(complexity), OPUS_ORACLE_VBR=str(vbr),
                              OPUS_ORACLE_FEC=str(fec), OPUS_ORACLE_LOSS=str(loss))
            pcm.write_bytes(pcm_input(size * frames, channels, pattern))
            output = run(ROOT / f"target/reference{suffix}/opus-reference", [str(rate), str(channels), str(size), str(frames), "1000", str(24000 * channels), str(pcm)])
            records.append("S " + " ".join(map(str, configuration)))
            for line in output.splitlines():
                fields = line.split("\t")
                if fields[4] != fields[5] or fields[4] != fields[6]:
                    raise RuntimeError("Reference entropy ranges differ")
                records.append(f"P {fields[4]} {fields[7]}")
    destination = ROOT / f"rust/tests/fixtures/reference/silk-encoder{suffix}.tsv"
    destination.write_text("\n".join(records) + "\n")
    print(f"Generated {len(configurations)} independent C encoder configurations: {destination}")


if __name__ == "__main__":
    main()
