#!/usr/bin/env python3
"""Generate OSCE model dimensions and layer specifications from pinned model exports."""
import argparse
import pathlib
import re

p = argparse.ArgumentParser(__doc__)
p.add_argument('model_directory', type=pathlib.Path)
p.add_argument('--output', type=pathlib.Path, default=pathlib.Path('rust/src/osce/model_specs.rs'))
a = p.parse_args()
output = ['// Generated by tools/reference/generate_osce_specs.py from the pinned Opus model exports.', '#![allow(dead_code, unused_parens, clippy::excessive_precision)]', 'use super::{LayerSpec, OwnedLayer};', 'use crate::dnn_weights::{WeightBlob, WeightError};']
for model, cls in [('lace','LaceLayers'),('nolace','NoLaceLayers'),('bbwenet','BbweLayers')]:
    header=(a.model_directory/f'{model}_data.h').read_text()
    for name, value in re.findall(r'^#define\s+(\w+)\s+([^\n]+)', header, re.M):
        if not name.startswith(model.upper()+'_') or not re.fullmatch(r'[\d.eE+\-f *()]+',value.strip()): continue
        value=value.strip()
        floating='.' in value or value.endswith('f')
        output.append(f'pub(crate) const {name}: {"f32" if floating else "usize"} = {value.rstrip("f")};')
    source=(a.model_directory/f'{model}_data.c').read_text()
    entries=[]
    for name,args in re.findall(r'linear_init\(&model->(\w+), arrays,\s*([^;]+?)\)\)', source):
        fields=[x.strip() for x in args.split(',')]
        assert len(fields)==9,(name,fields)
        entries.append((name,fields))
    output += ['#[derive(Clone, Debug)]',f'pub(crate) struct {cls} {{']+[f'    pub {name}: OwnedLayer,' for name,_ in entries]+['}']
    output += [f'impl {cls} {{', '    pub fn load(blob: &WeightBlob<\'_>) -> Result<Self, WeightError> {', '        Ok(Self {']
    for name,fields in entries:
        names=', '.join('None' if x=='NULL' else f'Some({x})' for x in fields[:7])
        output.append(f'            {name}: OwnedLayer::load(blob, LayerSpec {{ names: [{names}], inputs: {fields[7]}, outputs: {fields[8]} }})?,')
    output+=['        })','    }','}']
a.output.write_text('\n'.join(output)+'\n')
